# Generated by Django 4.2.6 on 2023-11-29 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_devices"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("seven", models.BooleanField(default=True)),
                ("eight", models.BooleanField(default=True)),
                ("nine", models.BooleanField(default=True)),
                ("ten", models.BooleanField(default=True)),
                ("eleven", models.BooleanField(default=True)),
                ("tweleve", models.BooleanField(default=True)),
                ("thirteen", models.BooleanField(default=True)),
                ("forteen", models.BooleanField(default=True)),
                ("fifteen", models.BooleanField(default=True)),
                ("sixteen", models.BooleanField(default=True)),
                ("seventeen", models.BooleanField(default=True)),
                ("eighteen", models.BooleanField(default=True)),
                ("nineteen", models.BooleanField(default=True)),
                (
                    "devices",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.devices",
                    ),
                ),
            ],
        ),
    ]
