# Generated by Django 4.2.6 on 2023-11-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_bookappointments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviceprice",
            name="device",
        ),
        migrations.AddField(
            model_name="deviceprice",
            name="problem_kind",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
