# Generated by Django 4.2.6 on 2023-11-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0005_remove_deviceprice_device_deviceprice_problem_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceprice",
            name="brand",
            field=models.CharField(
                blank=True, default="others", max_length=100, null=True
            ),
        ),
    ]
