# Generated by Django 4.2.6 on 2023-12-04 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer", "0006_deviceprice_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "devices",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.devices",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Timeframe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("7:00 AM", "7:00 AM"),
                            ("8:00 AM", "8:00 AM"),
                            ("9:00 AM", "9:00 AM"),
                            ("10:00 AM", "10:00 AM"),
                            ("11:00 AM", "11:00 AM"),
                            ("12:00 PM", "12:00 PM"),
                            ("1:00 PM", "1:00 PM"),
                            ("2:00 PM", "2:00 PM"),
                            ("3:00 PM", "3:00 PM"),
                            ("4:00 PM", "4:00 PM"),
                            ("5:00 PM", "5:00 PM"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "appointments",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.appointments",
                    ),
                ),
            ],
        ),
    ]
