# Generated by Django 4.2.6 on 2023-12-04 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0008_alter_timeframe_timeframe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeframe",
            old_name="timeframe",
            new_name="timeframes",
        ),
    ]
